# Generated by Django 5.1.7 on 2025-03-13 21:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('billetterie', 'Billetterie'), ('inscription', 'Inscription Personnalisée')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('location_address', models.TextField()),
                ('location_city', models.CharField(max_length=100)),
                ('location_country', models.CharField(default='Cameroun', max_length=100)),
                ('location_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('validated', 'Validé'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('registration_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form_storage_usage', models.FloatField(default=0.0)),
                ('form_active_days', models.PositiveIntegerField(default=0)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
                ('gallery_images', models.ManyToManyField(blank=True, related_name='events', to='events.eventimage')),
                ('tags', models.ManyToManyField(blank=True, related_name='events', to='events.eventtag')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('textarea', 'Zone de texte'), ('number', 'Nombre'), ('email', 'Email'), ('phone', 'Téléphone'), ('date', 'Date'), ('time', 'Heure'), ('select', 'Liste déroulante'), ('checkbox', 'Case à cocher'), ('radio', 'Boutons radio'), ('file', 'Fichier')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('options', models.TextField(blank=True, help_text='Options séparées par des virgules (pour select, checkbox, radio)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
