# Generated by Django 5.1.7 on 2025-04-16 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_add_message_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessagingsettings',
            options={'verbose_name': 'Paramètres de messagerie', 'verbose_name_plural': 'Paramètres de messagerie'},
        ),
    ]
