# Generated by Django 5.1.7 on 2025-03-13 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('event_update', "Mise à jour d'événement"), ('registration_confirmation', "Confirmation d'inscription"), ('payment_confirmation', 'Confirmation de paiement'), ('event_reminder', "Rappel d'événement"), ('system_message', 'Message système'), ('custom_message', 'Message personnalisé')], max_length=30)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('sms_body', models.TextField(blank=True)),
                ('push_title', models.CharField(blank=True, max_length=255)),
                ('push_body', models.TextField(blank=True)),
                ('in_app_title', models.CharField(blank=True, max_length=255)),
                ('in_app_body', models.TextField(blank=True)),
                ('available_variables', models.TextField(blank=True, help_text='Liste des variables utilisables dans ce modèle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('event_update', "Mise à jour d'événement"), ('registration_confirmation', "Confirmation d'inscription"), ('payment_confirmation', 'Confirmation de paiement'), ('event_reminder', "Rappel d'événement"), ('system_message', 'Message système'), ('custom_message', 'Message personnalisé')], max_length=30)),
                ('related_object_id', models.CharField(blank=True, max_length=50)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Notification push'), ('in_app', "Dans l'application")], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
